- composer.json
- composer.lock
* The Symfony 3.0 branch chose for php >= 5.5.9 so you should require `symfony/finder:~2.7`
* You should suggest using `ext-gmp` instead of requiring it. My installation crashed on this, TBG does not rely on it.
* The `autoload` classmap is not needed, because B2DB is required via Composer seperately and `core/` already is in the `psr-4` autoload
> Fix Composer install process

- core/modules/main/cli/Install.php
This pull request fixes the installation of TBG using the CLI when database configuration file is already present. Useful for quicker testing of installation process (from CLI at least).
> Fix reuse of database configuration during CLI installation

- core/entities/User.php
Once the regular authentication methods have been attempted, if user is still not logged-in, and login is not required (guest access is denied), log-in the user with a guest account. Resolves issue #2518.
I have not been able to verify this patch works against actual master since I could not install from master. However, I did test the patch against the tag v4.0-rc.1, and there it has worked as expected. I'm not 100% sure I understand what the "Guest user is authenticated" option does, and if I should take it into account somehow, though.
> Fix for guest user access

- modules/agile/templates/_milestonefinish.inc.php
After refactoring of Agile module routing for "agile_markmilestonefinished"
was not updated in related template. This change fixes this.
Signed-off-by: Vesa Jääskeläinen <dachaac@gmail.com>
> Agile: Fix routing for "Mark as finished" for milestone.

- core/entities/User.php
Do not set login cookies for guest users. Fixes regression from pull request for issue #2518 that made it almost impossible to login.
> Make it possible for users to log in (regression fix for pull #332)

- core/modules/configuration/templates/_issuetype.inc.php
- core/modules/configuration/templates/configureissuetypes.html.php
When configuring an issuetype scheme, the dropdown box for the
"Redirect" option was always larger than the box it was embedded into.
Since word wrap is not possible for plain HTML select boxes the whole
"Configure issue types" style needed to be adapted a little bit. It is
now 50 pixel larger than the other tabs (which no one notices) and the
size of the select boxes (including padding) were adapted.
> Change style for "Configure issue types" and "Issuetype scheme" proposal

- composer.json
- core/modules/installation/Actions.php
... so one step less is needed during the installation process
> create cache folder via composer post-install-cmd

- core/framework/Context.php
- core/framework/Response.php
Add a new layout_path property to the Response class and two new events
to Context so themes and modules can hook into the rendering and change
the layout and offline template paths. This will enable themes and
modules to override the default layout without editing core files.
Example:
```php                                                                                                                     
framework\Event::listen('core', '\thebuggenie\core\framework\Context::renderBegins', array($this, 'renderBegins'));
public function renderBegins() 
{
// this will result in loading /var/www/thebuggenie/themes/custom/templates/layout.php
framework\Context::getResponse()->setLayoutPath('/var/www/thebuggenie/themes/custom/templates');
}                                            
```
> Add the ability for themes to override the layout

- core/modules/main/fixtures/emptymoduleclass
The table annotation is missing from the current empty module class
fixture, therefore the newly generated empty modules will throw an error
at installation, eg.:
> The class '\thebuggenie\modules\newmodule\Newmodule' is missing a valid @Table annotation
> An exception was thrown in the B2DB framework
> Add table annotation to empty module class fixture

- core/entities/Module.php
- core/framework/Context.php
- core/framework/Routing.php
VCS integrations need to have a possibility to make requests without requiring login. Passkey will be used to authenticate VCS web hook. This change makes it possible to configure in VCS code itself how it needs to behave. Same mechanism can be used for other pages like /login in future to remove fixed list of anonymous routes.
Both routes.yml/anonymous_route:true and @AnonymousRoute annotation is supported.
Signed-off-by: Vesa Jääskeläinen <dachaac@gmail.com>
> Made it possible to configure anonymous routes in route configuration.

- core/entities/User.php
- core/framework/Settings.php
- core/modules/configuration/Actions.php
- core/modules/configuration/templates/_user.inc.php
- modules/mailing/Mailing.php
- modules/mailing/templates/_articlecomment.html.inc.php
- modules/mailing/templates/_articlecomment.text.inc.php
- modules/mailing/templates/_articleupdate.html.inc.php
- modules/mailing/templates/_articleupdate.text.inc.php
- modules/mailing/templates/_issuecomment.html.inc.php
- modules/mailing/templates/_issuecomment.text.inc.php
- modules/mailing/templates/_issuecreate.html.inc.php
- modules/mailing/templates/_issuecreate.text.inc.php
- modules/mailing/templates/_issuesubscribed.html.inc.php
- modules/mailing/templates/_issuesubscribed.text.inc.php
- modules/mailing/templates/_issueupdate.html.inc.php
- modules/mailing/templates/_issueupdate.text.inc.php
Added support to configure display name formatting for users.
Settings->Users & Security->User's display name format.
It allows two configurations:
- Prefer buddy (default -- current functionality)
- Prefer real name
Change affects Issue/project view where users are listed and also to emails.
> Displayname formatting

- core/entities/Issue.php
When time spent is logged hours are logged with multiplier of 100. It needs to
be taken into account when logging amount of hours previously the issue had.
This fixes email reporting of issue changes when hours are added for the task.
Signed-off-by: Vesa Jääskeläinen dachaac@gmail.com
> Fix reporting of time spent for hour units.

- core/config/b2db.sample.yml
Without quotes, upgrades will fail when people are using complex passwords.
> Quotes are required around the DB password

- core/templates/footer.inc.php
Due changes on 9a29220 cause footer to show html entity on string text.
> fix stop showing html entity on footer template

- core/framework/I18n.php
I noticed that some timezones were displayed incorrectly in the TBG timezone drop down list. The code currently does this: 
```php
foreach ($info as $zone)
{
if (!empty($zone['timezone_id'])
AND
!in_array($zone['timezone_id'], $added)
AND
in_array($zone['timezone_id'], $idents))
{
$z = new DateTimeZone($zone['timezone_id']);
$c = new DateTime(null, $z);
$zone['time'] = $c->format('H:i a');
$data[] = $zone;
$offset[] = $z->getOffset($c);
$added[] = $zone['timezone_id'];
}
}
```
There may be multiple zones matching a particular timezone_id, to account for historical changes to daylight savings periods etc. The existing code accounts for that using the $added[] array so that each timezone_id is processed only once. The correct zone associated with the current time is determined by …
> Improve timezone selection list

- core/entities/Milestone.php
spent time in hours in burndown graph was calculated with estimate hours by unit minus spent times hours by multiple of 100
> fix burndown spent times

- core/lib/common.inc.php
When tbg_formatTime() attempts to display recent days as Yesterday, Today or Tomorrow it uses the following approach:
```php
$tstamp += tbg_get_timezone_offset();
if (date('dmY', $tstamp) == date('dmY'))
{
$tstring .= __('Today') . ', ';
}
elseif (date('dmY', $tstamp) == date('dmY', mktime(0, 0, 0, date('m'), (date('d') - 1))))
{
$tstring .= __('Yesterday') . ', ';
}
elseif (date('dmY', $tstamp) == date('dmY', mktime(0, 0, 0, date('m'), (date('d') + 1))))
{
$tstring .= __('Tomorrow') . ', ';
}
```
$tstamp is corrected for the desired timezone and then 'dmY' is calculated for $tstamp and compared against the current 'dmY'. However the current 'dmY' is not timezone corrected.
In some cases this results in the wrong day being displayed. For example, let $tstamp = 2015-06-18T20:00Z and assume …
> Correct the calculation of Today, Yesterday, Tomorrow for timezone

- core/modules/search/Actions.php
This commit resolves the following error that occurs when using the "Jump to an Issue" for a project listed on the front page:
```
array_shift() expects parameter 1 to be array, null given
The following error occured:
array_shift() expects parameter 1 to be array, null given in /thebuggenie/core/modules/search/Actions.php, line 199 
```
> Fix jump to an issue

- core/entities/Issue.php
- core/entities/Status.php
- core/lib/ui.inc.php
Function "hex2rgb" Introduced in ab4bee79af635a2466556217d9947656673f3beb didn't account for empty variable "$colour". 
Credits to @dachaac for spotting it and proposing this solution. :)
> Fix bug when variable "$colour" is empty string.

- modules/publish/entities/tables/ArticleLinks.php
- modules/publish/templates/_specialdeadendpages.inc.php
The wiki dead end and orphaned special page are interchanged - the dead end list displays orphaned pages and vice-versa.
> Fix the deadend pages list and orphaned pages list

- modules/vcs_integration/Actions.php
- modules/vcs_integration/cli/Report.php
The vcs-integration module supports specifying a single revision when reporting a commit providing the new revision is an integer. However the integer detection does not work because is_integer() tests the _type_ of the variable rather than the content and always reports false for a string.
> To test if a variable is a number or a numeric string (such as form input, which is always a string), you must use is_numeric().
http://php.net/manual/en/function.is-int.php
Rather than use is_numeric() as recommended by the PHP manual, which would also return true for a non-integer numeric, ctype_digit() is a simple alternative that will check a string for pure integer content.
> Returns TRUE if every character in the string text is a decimal digit, FALSE otherwise. …
> Fix integer detection for vcs commit revision

- core/framework/Routing.php
- core/modules/main/Actions.php
- modules/vcs_integration/Actions.php
The core\framework\Request object populates the request parameters from `$_GET` and `$_POST`:
```php
foreach ($_POST as $key => $value)
{
$this->_post_parameters[$key] = $value;
$this->_request_parameters[$key] = $value;
}
foreach ($_GET as $key => $value)
{
$this->_get_parameters[$key] = $value;
$this->_request_parameters[$key] = $value;
}
```
This data is already decoded and does not require additional `urldecode()`:
> Warning
The superglobals `$_GET` and `$_REQUEST` are already decoded. Using `urldecode()` on an element in `$_GET` or `$_REQUEST` could have unexpected and dangerous results.
http://php.net/manual/en/function.urldecode.php
The warning does not explicitly mention `$_POST`, and I haven't found any explicit documentation indicating that `$_POST` data is already decoded, but …
> Do not urldecode() request parameters since PHP has already decoded them

- core/helpers/TextParser.php
The regular expression for parsing html entities contains a greedy `.*` that will match up to the last semicolon. For example, the sequence `&amp; &amp; &gt;` is treated as a single entity, with the result that the second `&amp;` and the `&gt;` are not detected as html entities.
The `CHAR_REFS_REGEX` regular expression from the mediawiki Sanitizer.php can be adapted to tame the greediness.
https://github.com/wikimedia/mediawiki/blob/master/includes/Sanitizer.php
> Improve precision of special char parsing

- modules/publish/Publish.php
The permissions check applied to an article short-circuits if access is either explicitly granted or denied for that article. The permissions check for parent namespaces of an article only short-circuits if permission has been granted. For consistency, I believe this should follow the same model as the permissions check for the article itself so that denying access to a namespace denies access to all child articles, unless explicitly overridden on the child article.
> fix permissions applied to parent namespaces of wiki articles

- core/helpers/TextParser.php
One of my previous PRs contained a couple of dodgy characters in the special chars regex. I'm sorry to increase your workload by having to submit an additional PR to fix my error.
> Remove dodgy characters that snuck into the special chars regex

- core/modules/main/Actions.php
This is a preparatory commit to provide a code path to support streaming uploaded files (attachments etc) directly from the database. No immediate impact is anticipated. An additional companion b2db PR is required to activate this code path.
The driving motivation for this is to properly support storage of uploaded files within postgresql, which requires binary data to be escaped when inserted into a bytea column:
http://php.net/manual/en/function.pg-escape-bytea.php
If the data is not properly escaped an error similar to the following occurs when inserting the data:
> ERROR: invalid byte sequence for encoding "UTF8": 0x89
PHP's PDO provides built-in support for reading and writing binary data, and also supports streaming data from the database.
http://php.net/manual/en/pdo.lobs.php …
> Preliminary support for DB streaming

- core/modules/configuration/templates/configureuploads.html.php
- core/modules/configuration/templates/settings.html.php
- core/modules/project/templates/_projectedition.inc.php
The `__()` function performs HTML entity encoding by default so there is no need to pre-encode HTML entities. Doing so results in double encoding which then appears in the rendered text. For example the **Configure uploads & attachments** page heading appears as **Configure uploads &amp;amp; attachments**.
> Remove redundant HTML entity encoding from labels

- core/modules/main/templates/_intro_index_single_tracker.inc.php
- modules/publish/entities/Article.php
Replace `Configure &ndash;&gt; Settings` with `Configure &rarr; Settings` and prevent redundant html entity encoding which results in the html entities appearing encoded in the UI.
Do not apply `html_entity_decode()` to the wiki text prior to parsing when extracting links and categories. This step is not done during regular wiki text parsing in `getParsedContent()` and so introduces an inconsistency which can in rare cases result in the detection of phantom links. For example, if the text contains `&#x5b;&#x5b;otherpage]]` then the regular parsing does not detect a link, but that will be treated as a link for the purpose of link detection.
> Remove redundant html entity encoding / decoding

- modules/publish/templates/_articledisplay.inc.php
The categories box is present even when a wiki article has no categories. This diverts attention away from the content of the article and adds no useful information. This commit omits the category box when there are no categories (which is consistent with mediawiki behaviour). The bold is also removed from the word Categories so that when the category box is displayed it is less attention grabbing.
> Do not display the category box on wiki articles when there are no categories

- public/js/thebuggenie/tbg.js
Some pages do not contain a #searchfor element and attempts to initialise the auto-completer result in a javascript error. For example, from the login page:
>Uncaught TypeError: Cannot read property 'value' of null
Autocompleter.Base.Class.create.baseInitialize (controls.js:53)
Ajax.Autocompleter.Class.create.initialize (controls.js:370)
klass (prototype.js:101)
TBG.Core._initializeAutocompleter (tbg.js?bust=4.0.2:110)
TBG.initialize (tbg.js?bust=4.0.2:425)
f_init (login:286)
(anonymous function) (login:287)
runCallbacks (domReady.js:24)
callReady (domReady.js:35)
pageLoaded (domReady.js:50)
The commit also takes the liberty of removing some commented code.
> Do not attempt to initialise the Autocompleter if there is no #searchfor element

- core/modules/search/templates/findissues.html.php
$searchtitle should already be translated here, so a second translation would mask special character encoding like german umlaute
> prevent from repeated translation

- core/helpers/TextParser.php
Permit sub and sup tags in wiki pages to support subscript and superscript text.
> Support sub and sup html elements in wiki articles

- core/framework/Settings.php
- core/modules/configuration/controllers/Main.php
- core/modules/configuration/templates/_general.inc.php
- core/modules/main/controllers/Main.php
- public/js/thebuggenie/tbg.js
The poll interval for user notifications is 10 seconds. If there are n users each with an average of m buggenie tabs open then the polling query rate is n x m / 10 which can become significant. This commit adds a setting to allow administrators to control the poll rate, potentially disabling it entirely by setting to zero.
> Add a setting to control the notification poll interval

- core/framework/Settings.php
Translation of text containing ampersand does not work well if translated with transifex and xlf. E.g. "Uploads & attachments" will get "Uploads &amp;amp; attachments" in xlf. Because the original language string does not match, text would not be translated.
> Replaced ampersand in setting titles

- modules/publish/css/publish.css
- modules/publish/templates/editarticle.html.php
Even when the change reason is set to be optional a separate prompt occurs to allow a comment to be specified after clicking save on a wiki article. This commit places the comment box on the edit page to avoid the need for an extra step.
> Include the wiki edit comment text box on the edit page directly

- core/entities/tables/Settings.php
- core/framework/Response.php
- core/framework/Settings.php
- core/modules/configuration/controllers/Main.php
- core/modules/configuration/templates/configureuploads.html.php
- core/modules/main/controllers/Main.php
We're using The Bug Genie on European servers and accessing it from all around the world. Therefore bandwidth optimization and server performance is a very important issue.
These changes contain two optimizations:
- Image file resources can be sent to the client browsers with valid caching headers, allowing them to be cached by browsers and reducing last modified requests.
- File resources can be delivered using the X-Sendfile server extension allowing huge files to be sent directly by the server without breaking down on PHP's memory_limit.
Both settings are optional and can be enabled from within The Bug Genie's "Uploads & attachments" settings.
> Allow image file caching and file delivery using x-sendfile

- core/entities/Comment.php
This overcomes the following error when editing an article comment:
> PHP Fatal error:  Class 'thebuggenie\\core\\entities\\tables\\Articles' not found in /thebuggenie/core/entities/Comment.php on line 626
> Fix for editing article comments

- modules/publish/css/publish.css
A previous pull request introduced support for an inline change reason comment field when editing wiki articles. This resulted in poor positioning of the comment field when in distraction free editing mode. This commit aims to rectify that by moving the Comment field below the edit area.
> Fix the positioning of the comment field when editing wiki articles in distraction free editing mode

- core/framework/Context.php
- core/framework/Response.php
- core/modules/configuration/controllers/Main.php
- core/modules/configuration/templates/_leftmenu.inc.php
- core/modules/import/controllers/Main.php
- core/modules/main/templates/about.html.php
- core/modules/main/templates/clientdashboard.html.php
- core/modules/main/templates/dashboard.html.php
- core/modules/main/templates/index.html.php
- core/modules/main/templates/myaccount.html.php
- core/modules/main/templates/reportissue.html.php
- core/modules/main/templates/teamdashboard.html.php
- core/modules/main/templates/viewissue.html.php
- core/modules/project/templates/dashboard.html.php
- core/modules/project/templates/files.html.php
- core/modules/project/templates/releasecenter.html.php
- core/modules/project/templates/releases.html.php
- core/modules/project/templates/roadmap.html.php
- core/modules/project/templates/settings.html.php
- core/modules/project/templates/statistics.html.php
- core/modules/project/templates/team.html.php
- core/modules/project/templates/timeline.html.php
- core/modules/search/templates/findissues.html.php
- core/templates/submenu.inc.php
- modules/agile/templates/board.html.php
- modules/agile/templates/index.html.php
- modules/agile/templates/whiteboard.html.php
- modules/publish/Publish.php
- modules/publish/templates/_wikibreadcrumbs.inc.php
- modules/vcs_integration/templates/projectcommits.html.php
I recently discovered that the chevron between breadcrumbs supports a drop-down menu with links related to that breadcrumb. To me this was a wow feature! :)
I am interested in taking this model further so that the breadcrumbs are a first class way of navigating TBG. This has also sparked some ideas for further work on the top menus to work in tandem with the breadcrumbs (for future commits).
At present when a breadcrumb is added using `Response::addBreadcrumb()` the specified subitems apply to the chevron _preceding_ the breadcrumb being added. That means the list generally must contain alternate sibling nodes (alternative places you could have got to from the same parent if you didn't end up on the current path). However, it is more natural to specify alternative siblings when creating …
> Restructure breadcrumbs

- core/modules/main/fixtures/emptymoduleclass
The cli generates a new module without the `$_name property`, resulting in
the following error on the module configuration page:
```
Route named "configure_install_module" have a mandatory "module_key"
parameter
```
> Add name property to empty module fixture

- core/framework/ActionComponent.php
- core/framework/Context.php
The commit enables action and component template files to have subdirectories in the path definition. This will enable modules which overwrite multiple template files to organize the template files into subdirectories.
Before the commit template files needed to be organized with prefixes:
```
└── module
└── templates
├── main_index.html.php
├── _main_menulinks.inc.php
├── publish_showarticle.html.php
└── _publish_articledisplay.inc.php
```
After the commit template files can be organized into subdirectories:
```
└── module
└── templates
├── main
│   ├── index.html.php
│   └── _menulinks.inc.php
└── publish
├── showarticle.html.php
└── _articledisplay.inc.php
```
> Enable subdirectories for template files

- core/framework/I18n.php
Currently, module xlf translation filenames look like this "agile.xlf", not like "strings.xlf"
> Prefer xlf files where filename is modulename

- core/framework/Cache.php
Currently the installer fails if the `cache` directory is missing.
This PR attemps to create the `cache` directory (and fail the same if the permission do not allow it)
> Try to create the cache directory if inexistent

- modules/publish/entities/Article.php
This line prevented the installation to run to the end.
> Check that a user is returned before trying to fetch its ID

- modules/mailing/classes/TBGMailer.class.php
Hebrew mails were not seen correctly, may help other langs as well
, should not have negative effects
> EMails : Encode subject with utf-8 (to support other languages)

- core/modules/main/controllers/Main.php
Added an extra header for nginx X-Accel-Redirect.
The following configuration is required in nginx:
````
location ~* /files/(.*)\.(.*) {
internal;
root /home/www-sam/sites/bugtracker;
}
````
Explanation: 
- Match anything in /files containing a "." -- this is to exclude the /files/show url which should be routed to php.
- Internal so it is still private.
- Set the root to 1 level higher than the files dir.
Have confirmed that the `X-Sendfile` header does not interfere with Nginx, have not confirmed that the `X-Accel-Redirect` does not interfere with Apache / others.
> Add support for NGINX X-Sendfile variant: X-Accel-Redirect

- core/helpers/TextParser.php
When i made a new issue with a ref. to an existing issue i got a 500 internal server error the log showed to following:
[29-Jan-2016 07:07:14 UTC] PHP Fatal error:  Call to undefined function thebuggenie\core\helpers\make_url() in /core/helpers/TextParser.php on line 704
The changes in this file fixed it.
> Fix for: Call to undefined function thebuggenie\core\helpers\make_url()

- core/entities/Comment.php
- core/entities/DatatypeBase.php
- core/entities/Issue.php
- core/entities/Issuetype.php
- core/entities/Milestone.php
- core/entities/Project.php
- core/entities/Team.php
- core/entities/User.php
- core/entities/Userstate.php
- core/entities/common/Colorizable.php
- core/entities/common/Identifiable.php
- core/entities/common/Keyable.php
- core/entities/common/Ownable.php
- core/entities/common/QaLeadable.php
- core/entities/common/Releaseable.php
Reason is that non detailed output currently breaks logic in interface (eg. for automatic whiteboard refreshing, issue needs milestone). Anothor reason is that tracking broken logic would require too much time manually (without tests). Also added returning of array for Milestone entity method toJSON.
(cherry picked from commit 73a5a81)
> Changed default value for parameter "detailed" of toJSON method.

- core/modules/main/templates/_updateissueproperties.inc.php
When asking for user information on a workflow transition, text fields and text areas would be wrapped inside a select tag.
> Fix fields on workflow transition form

- composer.json
- composer.lock
- core/modules/installation/controllers/Main.php
Right now if you install via the downloaded .zip file, the symlink isn't there anymore. The images folder of the basic theme should be linked though.
This PR lets the composer scripts check if `/public/images` exists and otherwise symlinks it to `/themes/oxygen/images`.
Next to that, because `composer.lock` also is added to this project I did a `composer update` too.
> Check /images symlink on composer installation process

- modules/mailing/controllers/Main.php
Forgot password dialog asks for username or mail address, so if no username was found we should also check for e-mail addresses
> Check for mail address when checking forgotten password

- modules/publish/templates/articlepermissions.html.php
Width is ignored for the first item anyway, so second and thirth items width differ from first. Removing width equalises all items.
> Remove style property width for permission lists

- core/modules/main/templates/_logitem.inc.php
Old log records (previous TBG version 4.0) do not have any valid 'previous_value' or 'current_value'. Building the timeline will crash when we call formatTimeableLog with NULL values.
> Check LOG_ISSUE_TIME_SPENT for existing values

- core/framework/Response.php
setCookie will work even if NOW or $expiration is a string
> Make sure third setCookie parameter is integer

- core/modules/installation/controllers/Main.php
- core/modules/installation/templates/installstep4.html.php
- core/modules/main/cli/Install.php
- core/templates/htaccess.template
- core/templates/user.ini.template
- public/.htaccess
The purpose of this pull request is to improve how the .htaccess is handled, making the template look identical to stock .htaccess shipped and to remove deployment of deprecated PHP options in .htaccess and .user.ini.
Having the .htaccess file harmonised helps with avoiding accidental git commits (assuming that most people working on TBG will use RewriteBase of /).
The following two options are removed from `.user.ini` (technically, whole file is removed since these are the only options it had) and `.htaccess`:
- magic_quotes_gpc
- register_globals
According to documentation at http://php.net/manual/en/security.magicquotes.what.php and http://php.net/manual/en/security.globals.php these two features have been completely removed in PHP 5.4.0 and have been marked as deprecated in PHP 5.3.0. …
> Improve .htaccess handling and remove deprecated PHP options

- themes/oxygen/css/theme.css
Prevents header line from resizing menu by hover-event (see also [line 2133](https://github.com/thebuggenie/thebuggenie/tree/master/themes/oxygen/css/theme.css#L2133) )
> Minor theme fix

- modules/vcs_integration/hooks/git/tbg-post-receive
I've fixed some issues  with the bundled git hook from TBG.
- The new script separates each commit in a push and reports them individually to tbg_cli. 
- It now includes the branch name/ref when calling tbg_cli
- Ignores tags, as it would go through all commits in the repo
I think these changes fixes issue #603 and issue #2111
> Git hook fixes

- core/modules/main/controllers/Main.php
Fixed how the expiration period is calculated for cookie used for granting elevated privileges. Method setCookie() expects interval, not absolute time.
> Elevated privileges expiration fix

- core/entities/Issue.php
- core/framework/Settings.php
- core/modules/installation/Upgrade.php
This pull request should fix the issue with finished milestones (all issues closed/resolved) that are still shown as overdue.
The pull request also touches slightly on the code for updating related issues in sprints. This has not been tested, though - if you happen to be able to do it and review it, that'd help greatly. Otherwise feel free to nudge me into checking it out myself - but I haven't worked with sprints that much :)
There is also upgrade code that will try to fix existing overdue milestones by forcing a status update on them. I bumped the version to 4.1.14, but not sure if it should be some other version in there (since we discussed earlier bumping to 4.2 due to previous big changes to permission check implementation).
> Fix for milestones where all issues are closed/resolved, but they still appear as overdue

- themes/oxygen/css/theme.css
The sections 'Description' and 'Steps to reproduce this issue' are
misplaced: the headers are not shown at all and the content is moved on
the right part of the screen. Removing 'float: left' from the CSS of
those headers and contents, the problem is resolved.
> Removed 'float' on CSS for description and step headers

- core/framework/Context.php
- core/lib/ui.inc.php
- core/modules/main/cli/Install.php
Fixed installation of The Bug Genie via CLI:
- Make sure to check for installation mode during context set-up irrespective if
we are running in GUI or CLI.
- Wrap definition of geshi_highlight function with a conditional to avoid
redeclare error. This error ocurred only within CLI for some reason.
- Fixed creation of installed file when installing via CLI. Installation string
was different compared to GUI installation.
> Fixed installation of The Bug Genie via CLI

- .gitignore
- core/helpers/Pagination.php
- core/helpers/TextParser.php
- core/modules/main/templates/_pagination.inc.php
- modules/publish/Components.php
- modules/publish/Publish.php
- modules/publish/configuration/routes.yml
- modules/publish/entities/ArticleRevision.php
- modules/publish/entities/tables/ArticleHistory.php
- modules/publish/public/css/publish.css
- modules/publish/templates/_specialcontributions.inc.php
- modules/publish/templates/_specialcontributors.inc.php
- modules/publish/templates/_specialspecialpages.inc.php
- themes/firehouse/css/theme.css
- themes/oxygen/css/theme.css
- themes/tanuki/css/theme.css
This pull requests takes care of the following items from issue #610:
2. List of all changes made to project wiki. (help tracking changes and wiki spam)
3. List of all changes made by particular user to project wiki (help tracking changes and wiki spam)
4. wiki links to empty pages should be in different color (not green)
Features implemented:
- Wiki links to empty pages will show-up in red (in oxygen and tanuki themes).
- New special page for listing user contributors:
- `Special:Contributors`
- `Special:PROJECT:Contributors`
- New special page for listing user contributions:
- `Special:Contributions`
- `Special:PROJECT:Contributions`
- Narrow down to specific user via `?user=USERNAME`.
- Specify page and page size via `?page_size=SIZE&page=PAGE`.
- Generated listings contain a bunch of …
> Features 2, 3 (list of contributions), and 4 (distinct missing page links) from issue #610

- modules/publish/entities/tables/ArticleHistory.php
Small fix for issue found during testing by @zegenie (renamed articles cannot be tracked properly in via article revisions).
> Fixed handling for article revisions where the related Article has benn deleted or renamed (issue #610)

- modules/vcs_integration/controllers/Main.php
- Do not use $this->access_level sicne it does not seem to be set anywhere for
controller.
- Perform check via User::canEditProjectDetails method of requesting user.
> Fixed permission check for editing project VCS integration settings (issue #2767)

- ansible/files/structure.ldif
- core/entities/User.php
- core/framework/Context.php
- modules/auth_ldap/Auth_ldap.php
- modules/auth_ldap/cli/Import.php
- modules/auth_ldap/cli/Prune.php
- modules/auth_ldap/cli/Test.php
- modules/auth_ldap/controllers/Main.php
- modules/auth_ldap/templates/_settings.inc.php
This set of changes involves some major refactoring of the LDAP module code. The following major changes are included:
- Update to error handler in core to ignore suppressed PHP errors (commands where `@` operator is used).
- Update to handling of auto-login functionality in the core.
- Updated to LDAP structure for Vagrant/Ansible dev machine in order to provide more variety for testing LDAP.
- Business logic in LDAP module has been moved outside of controller and into the module class making it more easily accessible elsewhere in the code.
- Business logic has been rewritten to be more resilient, better structured, and with less duplication of code.
- Removed defaults for a number of settings. These were applied during the save operation automatically, which could look confusing (you …
> LDAP module refactoring and CLI

- core/entities/User.php
- core/framework/Action.php
We're currently creating a JIRA REST API v2 compatible API module for The Bug Genie in order to widen the range of third-party applications that are able to interact with TBG.  
As the JIRA REST API has HTTP basic auth support, we added this authentication method to the TBG core for our API requests.
Would be great to having it integrated in TBG as well, so we don't have to patch it on every update.
PS.: We'll release our module to the public once it's fully functional. ;)
> Allow HTTP basic auth for API requests.

- core/modules/main/templates/_issuelogitem.inc.php
- core/modules/main/templates/viewissue.html.php
- modules/vcs_integration/Vcs_integration.php
- modules/vcs_integration/templates/_viewissue_activities_tab.inc.php
- modules/vcs_integration/templates/_viewissue_commits.inc.php
- themes/oxygen/css/theme.css
This is a proposed GUI enhancement for The Bug Genie.
One of the issues our developers had with the issue view, was finding the commit history or getting a fast overview of the issue history when the comments list is too long.
So we created a tabbed 'Activities' area right under the issue description and steps to reproduce. This area contains tabs for the comments, commits (when VCS integration is enabled), as well as the issue history.
We re-used the existing event triggers and the empty tab container within the issueview template (hoping it doesn't interfere with the closed source version).
> Issue View: Move comments, history and commits into tabbed activities

- core/framework/Context.php
Noticed, that intermediate permission levels (such as `caneditissuebasic`) which are children of top level permissions, but do have `details` permissions as well, won't be added to `Context::$_available_permission_paths`. Therefore the permissions check on such permissions will return false, even when the top level permission was set.
This merge request fixes this issue.
> Fix intermediate permission levels won't be added to permissions path.

- core/entities/Issue.php
When changing issue types, the issue remains in the old issue type's workflow scheme. This fix also alters the issue's current workflow step to the new issue type's first workflow step, when the issue type changes.
In the current TBG dev version, this pull request depends on pull request #502, as issue types can't be changed otherwise.
> Issue 2778: Change workflow step and status when issue type changes

- core/entities/Issue.php
- public/js/thebuggenie/tbg.js
… when new issue type is not saved.
Refined the issue type change. Disabled workflow transition buttons and prevented from status change after the issue type has been changed (but not saved).
Just to make sure the status and workflow step won't be messed up when the user changes all of 'em at once.
> Prevent from further status or workflow changes

- core/entities/User.php
- modules/mailing/controllers/Main.php
This pull request fixes issue #2783. Users will be created if they use a non-existing email address within the password reset dialog.
> Issue #2783: Do not create a non-existing user through password reset page

- core/framework/Context.php
This pull request addresses the following issues:
- During installation an error will occur because when permissions are being cached a call is being made to get the scope ID, which at that point does not exist yet. Therefore, permissions should be cached only when TBG is not in install mode.
> Do not cache permissions during installation

- core/framework/cli/Command.php
- core/modules/main/cli/Help.php
- Do not use colour when output goes to non-interactive
terminal (piping).
- Added ability to suppress colour output by setting an environment
variable (useful for automation).
> Improved handling of colour output in CLI:

- composer.json
- composer.lock
- Updated composer.json configuration file.
- PHP 5.6 has been dropped from the requirements.
- Required PHP version has been set to 7.0, 7.1, or 7.2.
- Platform has been pinned to PHP 7.0 to ensure that composer update
takes into account only versions of packages that are compatible
with it - irrespective of what the developer's PHP local version
might be.
- Updated the composer.lock file.
> Drop support for PHP 5.6, and lock platform to PHP 7.0:

- core/framework/Action.php
- Do not assume in Action base that by setting requested format in
request to one of json, rss, or xml that the authentication method
which should be used is application password.
- Indirectly fixes broken functionality for adding relations between
issues (this one failed because detected user ended-up being
detected as guest instead of actual user that is logged-in).
- Controllers that need to be more specific in regard to what type of
authentication method is supported should override the relevant
method explicitly.
> Do not assume application password authentication for non-HTML requested formats by default

- core/entities/Issue.php
- core/modules/main/configuration/routes.yml
- core/modules/main/controllers/Main.php
- core/modules/main/templates/_findduplicateissues.inc.php
- core/modules/main/templates/_findrelatedissues.inc.php
- core/modules/main/templates/_relateissue.inc.php
- core/modules/main/templates/_updateissueproperties.inc.php
- core/modules/main/templates/http400.json.php
- core/modules/main/templates/notfound.json.php
- public/js/thebuggenie/tbg.js
- themes/oxygen/css/theme.css
- themes/tanuki/css/theme.css
The purpose of this PR is to clean-up the code responsible for finding the related and duplicate issues, and presenting the user with appropriate choices. This is an initial PR, and some more rigorous verification would be welcome.
The refactor concentrates on:
- Separating views for finding related and duplicate issues since their presentation layers are quite different (have different needs).
- Grouping the possible related issues when presenting them to the user (exact match -> same project -> other projects by alphabetical sorting).
- Refactoring slightly how finding of issues works in order to be able to locate both exact match and free-text search issues at the same time.
Things to pay attention to:
- In addition to standard functionality, possibly paying some attention to how …
> Refactor and clean-up of code related to finding related and duplicate issues

- i18n/de_DE/strings.xlf
added missing text-piece in the German translation about highlighted changes.
The existing translation only contains half of the original English text.
> updated german translation

- core/entities/Scope.php
Allow tbg to be installed behind a proxy with different protocols by respecting [HTTP_X_FORWARDED_PROTO](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto).
Common use case scenario:
- You're using LetsEncrypt
- You want to run certbot in a central place, so that you don't have to hop on many servers every 90 days to renew the certificate
- You're using a proxy (like HAProxy) where it accepts all SSL connections and forwards it to non-https backends
To let backend servers know which protocol the proxy server accepted and for which URL scheme it should generate the URIs, it's common practice to use `X-Forwarded-Proto` which is a de-facto standard.
> HTTP_X_FORWARDED_PROTO Support

- core/entities/User.php
- core/framework/AuthenticationBackend.php
- core/framework/interfaces/AuthenticationProvider.php
- modules/auth_ldap/LdapAuthenticationBackend.php
I made some changes so the ldap authentication works again on >4.1.13 (also see https://forum.thebuggenie.org/d/9-ldap-auth-module )
I did not see a reason why it was using AUTHENTICATION_TYPE_PASSWORD, so I just reused the existing AuthenticationBackend using the TOKEN.
The change to User.php I made so HTTP auth is also working again as it looks to me that implementation got lost also.
It is possible that this is completely not what you want. This is what works for me to have 4.3 up and running. It may be of some use for others.
> Fix auth_ldap module to follow authentication implementation changes

- core/modules/project/templates/_projectsettings.inc.php
This is a bug introduced in commit 19296eb4bbfb4825447d63daa722d1a2eb534a5e.
The values for this field had been inverted.
> Fix for toggling project lock status when saving its settings

- core/entities/Comment.php
Notification emails for comments are:
* for new comments: sent twice
* for edited comments: not sent
In commit 7dc7251d105ef65f6805f4a872ab222892ad0d14, there is an "else" removed. Putting this back solves both problems as
* the notifications for new comments are already handled in core/modules/main/controllers/Main.php by the means of the Comment::createNew event.
* the Comment::_postSave event should (also) be called when a non-new comment is saved
> Fix for two notification emails for new comments and none for edited comments

- core/entities/Issue.php
No notifications was given to the user when no category is selected in the notification settings (or no category is given to the issue on creation).
Fixed by checking the same way as shouldAutomaticallySubscribeUser
> Fix notifications not shown on new issue

- modules/auth_ldap/LdapAuthenticationBackend.php
Passwords with html special characters in did not work as they got replaced by the corresponding html entity.
Maybe this problem occurs also on other places, but this fix has the least (possible) side-effects.
> Do not sanitize (htmlentities) username and password for LDAP login

- core/framework/Context.php
When checking a permission, currently there is a bug where its parents permissions are prioritized over its own setting.
This fix checks the target permission first, and if none is set, checks the parents upward until one is found.
If no permissions anywhere are set, it uses the existing behavior of returning null.
> Fix to check lowest level permission

- modules/agile/controllers/Main.php
Since adding an epic adds an issue to the board, it seems that the user should need to have permission to add an issue if they want to add an epic.  Right now it only requires permission to view the board.  A user might have view permission but not issue add permission, such as the case of a guest user.
This copies the issue add permission check (from runReportIssue()) into the add epic function in the agile module.
Note that it currently doesn't display an error message, it just silently fails (this would be a good improvement in future).
> Require issue add permission for adding epics

- modules/agile/controllers/Main.php
Currently, several operations that permit viewing agile boards also allow them to be modified.
It would be nice for operations that change agile boards to be restricted to users with a higher permission set.  IE, it would be useful to be able to show agile boards to guest users, without also allowing guest users to modify them.
This change expands the existing 'project_scrum' permission, which was previously only used to gate assigning milestones, to also gate several other modification checks.  (It seemed like this was intended to be like a scrum master type permission (?))
Note that it currently doesn't display an error message, or hide the edit buttons -- it just silently fails (this would be a good improvement in future).
> Require higher level permissions for agile changes

- core/modules/main/templates/_issuepermissions.inc.php
- core/modules/main/templates/_reportissue.inc.php
When creating or editing an issue, clicking 'Add a user or team' would never display the dropdown to add a user or team.  This change allows it to toggle that panel.
> Fix for Custom Access Policy add panel never displaying

- modules/vcs_integration/controllers/Main.php
- public/js/thebuggenie/tbg.js
Selecting branches in vcs_integration:commits did not work as the parameter name was change in javascript for livelink.
Selecting "All branches" gives "undefined" to php. I suppose this also fixes "All branches" in livelink.
> Use livelink parametername to get branch in vcs_integration, fix "All branches"

- composer.json
- composer.lock
- Instead of depending on PHP packages built specifically against the
version 8.x of lib-pcre, allow use of PHP packages built against
more recent library version as well. At the very least lib-pcre 10.x
works perfectly fine.
- Fixes issue #2878.
> Allow use of PHP packages built against lib-pcre 8.0+

- Vagrantfile
- ansible/files/mutex.conf
- ansible/files/servername.conf
- ansible/files/vhost.conf
- ansible/provision.yml
- ansible/templates/x509/apache2.cfg.j2
- ansible/templates/x509/slapd.cfg.j2
- Switch to using Debian 10 Buster (comes with PHP 7.3). Use
"official" Debian project images instead of the bento ones.
- Upgrade to using Ansible 2.9.x.
- Drop the use of mod_ruid2, since it is unmaintained, and has been
dropped from Debian 10 Buster.
- Update list of installed packages, and reorganise them slightly.
- Add comment sections to the provisioning playbook for better task
grouping/separation.
- Switch to running the web server as user vagrant (substitute for
mod_ruid2).
- Upgrade composer to latest 1.10.x release. Although 2.x has come out
as well, the 1.10.x works slightly better with Ansible 2.9.x.
- Small updates to the names of tasks (call it Apache httpd instead of
Apache2 in a couple of places.
- Configure Apache httpd default server name in order to supress
annoying …
> Update development environment set-up

- modules/vcs_integration/Vcs_integration.php
Removed default null value for date parameter in processCommit. Will be forbidden in PHP 8 and was never used anyway.
> Removed default value for date parameter
