thebuggenie/thebuggenie

modules/publish/Actions.php

Avoid fatal error when saving handbook article type in Wiki.

---

core/modules/project/templates/roadmap.html.php

Milestonebox has moved under agile module so the routing here needs to be also
updated to match that.
Signed-off-by: Vesa Jääskeläinen <dachaac@gmail.com>

Roadmap: Correct routing for roadmap's milestones

---

modules/agile/Actions.php

Typo and translation

---

core/modules/configuration/Actions.php
core/modules/configuration/templates/_permissionsblock.inc.php
core/modules/configuration/templates/_role.inc.php
core/modules/configuration/templates/configureprojects.html.php
core/modules/main/templates/_comment.inc.php
core/modules/project/templates/_projectconfig_container.inc.php
core/modules/project/templates/_projectpermissions.inc.php
core/templates/layout.php
thebuggenie/js/prototype.js
thebuggenie/js/thebuggenie.js
thebuggenie/themes/oxygen/oxygen.css

Fade 'fullpage_backdrop_content' element before 'fullpage_backdrop' appears so that content of previous ajax is not visiible to confuse user.

Hide content of Backdrop on show method before ajax

---

core/modules/configuration/Actions.php

This fix is related to issue #2516
Link:
http://issues.thebuggenie.com/thebuggenie/issues/2516

Add missing namespace

---

modules/publish/Actions.php

Fixed Bug #2526 - Fatal error in 4.00-RC1 when submitting changes to wiki articles
Problem occurs because the fully qualified namespace reference is declared for the use statement.

Unable to edit wiki articles

---

core/entities/Project.php
core/entities/WorkflowTransition.php
core/modules/configuration/configuration/routes.yml
core/modules/configuration/templates/_finduser_row_editable.inc.php
core/modules/configuration/templates/_workflowaddtransition.inc.php
core/modules/configuration/templates/configureworkflowtransition.html.php
core/modules/configuration/templates/findusers.html.php
core/modules/main/templates/_reportissue.inc.php
thebuggenie/js/thebuggenie.js

Mostly logical fixes on functionalities that were broken.
Commit 31557ca6165436327c348bc6068f31ebf141f6e5 includes fix talked about in PR thebuggenie/thebuggenie#345. @stolenbike Thanks for letting me fix it. :+1:

Additional logical fixes

---

core/entities/Module.php
core/framework/Settings.php
core/modules/main/Actions.php
modules/mailing/Actions.php
modules/mailing/Mailing.php

Due to couple of bugs no emails were sent for new comments.
These changes fix that problem.

Mailing fixes

---

core/helpers/TextParser.php
core/modules/main/Actions.php

Fix for Apache's error.log error for missing class when editing Wiki.
Remove extra space from named links in Wiki.

Wiki fixes

---

core/entities/Issue.php

I tried creating a bug report in the bugtracker (http://issues.thebuggenie.com) but i'm getting some errors there.
So this pull request fixes a bug that is not in your bugtracker.
Since it is a one liner I hope further documentation is not necessary. This has been tested on v4.0.1 and master.
Cheers,

Fixed missing namespace.

---

modules/mailing/cli/ProcessMailQueue.php
modules/mailing/entities/tables/MailQueueTable.php

The mailing module failed to send e-mails after the upgrade from 3.2.x to 4.0.1.
I have found some errors in the code and I fixed them.
With these fixes it send e-mails correctly.

Fixed Mailing module

---

core/modules/project/templates/_milestonedetails.inc.php
core/templates/layout.php

JS flot was not loading dashes plugin.

Fix burndown not showing estimate velocities

---

modules/agile/entities/AgileBoard.php
modules/agile/templates/_milestonefinish.inc.php

Fixes couple of issues related to agile board:
- Empty project without milestones caused error being generated
- Could not mark milestone finished
- Adds missing termination for select tag.

Agile board fixes

---

modules/publish/entities/Article.php
modules/publish/templates/_header.inc.php

Was broken by commit dca4f3664b6f93a36ce12e3a585899604c1a5184.
Fixes issue [#2600](http://issues.thebuggenie.com/thebuggenie/issues/2600).

Allow ":" (colons) character in wiki article title.

---

modules/agile/entities/AgileBoard.php

Same as commit 9eee9d0f9d8b1fd96b69d2ff395438f9f9a20cdd but applied to Backlog on Planning page.

Fixed sorting of Backlog issues.

---

core/modules/main/configuration/routes.yml

make assets publicly available

---

core/modules/main/templates/viewissue.html.php
modules/publish/templates/showarticle.html.php

Some minor tweaks to permission denied and missing issue error messages.

Improve issue/article access denied error text

---

modules/publish/controllers/Main.php
modules/publish/templates/_header.inc.php

Article categories have not been working properly, particularly categories in a project wiki.
This commit makes the category handling more consistent.

Fix for article categories

---

core/modules/configuration/templates/configureuploads.html.php

Forgot these file changes with my last pull request. Thanks @Premke for pointing it out.

Added missing settings for file caching headers

---

core/entities/User.php

A small fix for allowing guest access to TBG when using LDAP authentication.

Fix for issue #2617 (guest access with LDAP authentication)

---

core/helpers/TextParser.php
core/helpers/TextParserMarkdown.php
core/modules/configuration/templates/configuremodule.html.php
core/modules/main/controllers/Main.php
core/modules/main/fixtures/emptymoduleclass
core/modules/main/templates/_attachedfile.inc.php
core/modules/main/templates/_userdropdown_inline.inc.php
core/modules/project/templates/_overview.inc.php
core/templates/layout.php
modules/agile/Agile.php
modules/agile/templates/_projectlinks.inc.php
modules/publish/css/publish.css
modules/publish/entities/Article.php
modules/vcs_integration/Vcs_integration.php
modules/vcs_integration/configuration/routes.yml
modules/vcs_integration/controllers/Main.php
modules/vcs_integration/entities/Commit.php
modules/vcs_integration/templates/_commitbox.inc.php
public/js/scriptaculous.js
public/js/thebuggenie/tbg.js
themes/oxygen/css/theme.css
themes/oxygen/theme.php

There are no breaking changes. Though commit d3f6ad3 changes matching logic for attachments referenced in article to first match by column "real_filename" and then by (previously used) "name".

Couple of functionality and visual fixes

---

core/framework/I18n.php

fix for language that doesn't after setting saved 

---

core/modules/main/templates/_tutorial_planning.inc.php

The word "the" was repeated
Reported by sareche via transifex

Removed the repeated word "the"

---

core/config/settings.yml
core/entities/tables/WorkflowTransitionValidationRules.php
core/modules/installation/controllers/Main.php
core/modules/main/templates/_issuespenttimes.inc.php
modules/mailing/templates/_accountsettings.inc.php
modules/vcs_integration/Vcs_integration.php
public/index.php
public/js/prototype.js

Until better solution is implemented here is a quick fix for upgrading with versions in between 3.2 and 4.1.3.

Quick fix for version upgrade

---

composer.json

relates to https://github.com/thebuggenie/thebuggenie/commit/af8ed95b11ba0a630bd5eedd9492624a3f3a5261

Minimum PHP5.4

---

core/entities/User.php

This patch was invoked by error, when I tried to click "prune users" in
module "LDAP Authentication".

#2164 Fix regression error in v4.1.0

---

core/entities/User.php

Fix for php error:
PHP Fatal error:  Call to a member function authenticateApplicationPassword() on null in /thebuggenie/core/entities/User.php on line 665

Call to a member function authenticateApplicationPassword() on null

---

core/entities/Comment.php
core/entities/DatatypeBase.php
core/entities/Issue.php
core/entities/Issuetype.php
core/entities/Milestone.php
core/entities/Project.php
core/entities/Team.php
core/entities/User.php
core/entities/Userstate.php
core/entities/common/Colorizable.php
core/entities/common/Identifiable.php
core/entities/common/IdentifiableScoped.php
core/entities/common/Keyable.php
core/entities/common/Ownable.php
core/entities/common/QaLeadable.php
core/entities/common/Releaseable.php
core/framework/Settings.php
core/modules/remote/configuration/routes.yml
core/modules/remote/controllers/Main.php
core/modules/remote/templates/listissuetypes.json.php
core/modules/remote/templates/listprojects.json.php
core/modules/remote/templates/me.json.php
core/modules/remote/templates/status.json.php

This PR includes first forays into issue [#2649](http://issues.thebuggenie.com/thebuggenie/issues/2649)
It includes output optimization of the list commands (listprojects, listissuetypes and listfieldvalues) to have better compatibility & a new route that returns a basic status overview of the bug genie.
It's only a small step but I would like to have an opinion if I am going the right way with this.
EDIT:
There is now a central toJSON($detailed = false) function on various common entities that can be overridden by subclasses. (See Commit f35394c) Implementations form various entities are also included.
Also, Endpoint /me now prints out detailed information on the user currently logged in & accessing the API.

Work on API Overhaul

---

core/modules/search/controllers/Main.php
core/modules/search/templates/findissues.html.php

Fix "Update this saved search" checkbox
Fix "Don't show this again" on "Search Saved" infobox

Hukoeth patch 2

---

core/entities/ApplicationPassword.php
core/entities/User.php
core/modules/main/controllers/Main.php

Flow:
1. Create application password (visible, one-time-use) in user settings; existing process
2. Calculate hash (token), then crypt() the hash and store in DB; send visible PW to user
3. Call /api/authenticate with visible password. Password gets used, get hash (token) back
4. authenticate all subsequent requests using this token, which is crypt()ed and compared to value in db
This PR has a related PR in the API module.

Clean up & Fix application password generation & token authentication

---

core/modules/main/templates/myaccount.html.php

Reported by elgation via transifex

Spelling fix

---

core/modules/configuration/controllers/Main.php

As suggested by elgaton via transifex

Error message changed

---

core/modules/main/templates/_issuelogitem.inc.php

Layout looks broken if there's no icon for this type

Add icon for log type LOG_ISSUE_UPDATE

---

core/modules/main/templates/_logitem.inc.php

Like #476, but for estimated time

Check LOG_ISSUE_TIME_ESTIMATED for existing values

---

core/entities/Project.php
core/entities/Role.php
core/entities/RolePermission.php
core/entities/User.php
core/entities/tables/Permissions.php
core/entities/tables/ProjectAssignedTeams.php
core/entities/tables/ProjectAssignedUsers.php
core/framework/Context.php

Major updates on how the permissions are handled internally. Fixes and improves:
- Permission handling for roles.
- Algorithm used to check permissions.
- Inline documentation for permission-related calls.
Possible issues:
- Not sure how to handle permissions for wiki namespaces that got removed in the meantime (i.e. it might not be possible to set permissions for removed namespaces, but they will be affecting permission checks nevertheless).
- Initial permissions are more restrictive than before, might cause issues.

Permissions

---

composer.json
composer.lock
core/framework/Context.php
core/modules/configuration/controllers/Main.php
core/modules/main/cli/CheckForUpdates.php

- Moved the code for performing the check outside of configuration
controller into the Context class.
- Refactored the update check code to be slightly more robust.
- Added a new CLI command for checking if TBG is up-to-date or not.

Implemented CLI command for checking for updates:

---

core/templates/htaccess.template
public/.htaccess

This is a web server admin job and it is addressed in default Apache config files.
Blindly restricted access to dot files/folders can create integration problems.

Removed restriction for dot files/folders in htaccess.

---

core/entities/Issue.php
core/modules/main/templates/_todo.inc.php

- Icons were wrong (todos which are done are displayed at not done)
- Actions were wrong (todos which are done would be marked as done again)
- Fixed todo marking for comment id 0

2 Fixes for the TODO list functionality

---

core/modules/main/templates/_todo.inc.php

Signed-off-by: Felicia Hummel <felicia@drachenkatze.org>

Check if $comment is set, because in my case, $comment was null, which broke instanceof

---

core/entities/Issue.php
core/framework/Context.php

Signed-off-by: Felicia Hummel <felicia@drachenkatze.org>

Moved "canseeallissues" to the project level, so it can be configurable on a per-project basis

---

core/modules/main/controllers/Asset.php

Use the same mimetype evaluation algorithm as in core/entities/file.php

Check if function finfo_open exists

---

core/modules/project/controllers/Main.php

Use plural for 'edition' in error message

Typo fixed

---

core/entities/Issue.php

Progress bar showing issue actual time over issue estimated time was showing incorrect percentage due to wrong operator in Issue.php

Fix incorrect estimated issue time percent

---

core/helpers/ProjectActions.php
core/modules/main/controllers/Main.php

While I was looking at commit 59e3181b3116d7c2cef8c6c589e1a44c54c409b6 in pachno, I also saw these fixes. So I applied them on thebuggenie while I was there.

Fix getting the referer (backport from pachno)

---

core/framework/Routing.php
core/helpers/TextParser.php
core/modules/main/Components.php
core/modules/main/controllers/Main.php

I fixed the TextParser based on commit 59e3181b3116d7c2cef8c6c589e1a44c54c409b6 in pachno.
In the previous batch, the improved fix for login was missing. It does not have a component function as suggestion, but I guess the run function is the place to fix this.

Fix some more errors/notices in php 7.4
